/**
 * Universal Rules — Apply to ALL Indian companies regardless of type/size
 *
 * These are the bedrock compliances every registered entity must follow.
 * Conditions are minimal (mostly just country_code = IN).
 */

import type { ComplianceRule } from '../types'

export const UNIVERSAL_RULES: ComplianceRule[] = [
  // ── Income Tax ──────────────────────────────────────────────────────────

  {
    id: 'itr-annual',
    name: 'Income Tax Return (ITR) — Annual Filing',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 139(1)',
    authority: 'Income Tax Department',
    frequency: 'annual',
    dueDateFormula: 'months_after_fy_end:7,day:31', // Oct 31 for companies (audit required)
    dueDescription: '31st October (if audit required) / 31st July (no audit)',
    penalty: '₹5,000 late fee u/s 234F (₹1,000 if income < ₹5L). Interest u/s 234A on unpaid tax.',
    isCritical: true,
    documentsRequired: ['Balance Sheet', 'P&L Statement', 'Tax Computation', 'Form 26AS', 'AIS'],
    sourceUrl: 'https://incometaxindia.gov.in/pages/i-am/companies.aspx',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'Every company/entity registered in India must file ITR annually',
  },

  {
    id: 'advance-tax-q1',
    name: 'Advance Tax — Q1 Instalment (15%)',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 208 read with Section 211',
    authority: 'Income Tax Department',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:jun15,covers:Q1',
    dueDescription: '15th June — at least 15% of estimated tax',
    penalty: 'Interest u/s 234C at 1% per month on shortfall',
    isCritical: false,
    documentsRequired: ['Challan 280'],
    sourceUrl: 'https://incometaxindia.gov.in/pages/acts/income-tax-act.aspx',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'Not required if estimated tax liability < ₹10,000. Presumptive income (44AD) pays 100% by Mar 15.',
    applicabilityReason: 'All companies with estimated tax liability ≥ ₹10,000 must pay advance tax',
  },

  {
    id: 'advance-tax-q2',
    name: 'Advance Tax — Q2 Instalment (45%)',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 208 read with Section 211',
    authority: 'Income Tax Department',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:sep15,covers:Q2',
    dueDescription: '15th September — cumulative 45% of estimated tax',
    penalty: 'Interest u/s 234C at 1% per month on shortfall',
    isCritical: false,
    documentsRequired: ['Challan 280'],
    sourceUrl: 'https://incometaxindia.gov.in/pages/acts/income-tax-act.aspx',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'All companies with estimated tax liability ≥ ₹10,000 must pay advance tax',
  },

  {
    id: 'advance-tax-q3',
    name: 'Advance Tax — Q3 Instalment (75%)',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 208 read with Section 211',
    authority: 'Income Tax Department',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:dec15,covers:Q3',
    dueDescription: '15th December — cumulative 75% of estimated tax',
    penalty: 'Interest u/s 234C at 1% per month on shortfall',
    isCritical: false,
    documentsRequired: ['Challan 280'],
    sourceUrl: 'https://incometaxindia.gov.in/pages/acts/income-tax-act.aspx',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'All companies with estimated tax liability ≥ ₹10,000 must pay advance tax',
  },

  {
    id: 'advance-tax-q4',
    name: 'Advance Tax — Q4 Instalment (100%)',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 208 read with Section 211',
    authority: 'Income Tax Department',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:mar15,covers:Q4',
    dueDescription: '15th March — 100% of estimated tax',
    penalty: 'Interest u/s 234C at 1% per month on shortfall',
    isCritical: false,
    documentsRequired: ['Challan 280'],
    sourceUrl: 'https://incometaxindia.gov.in/pages/acts/income-tax-act.aspx',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'All companies with estimated tax liability ≥ ₹10,000 must pay advance tax',
  },

  {
    id: 'tds-return-q1',
    name: 'TDS Return (Form 140, formerly 24Q/26Q) — Q1',
    category: 'Income Tax',
    act: 'Income Tax Act, 2025 (formerly Income Tax Act, 1961)',
    section: 'Section 393 (formerly Section 200(3))',
    authority: 'Income Tax Department (TRACES)',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:jul31,covers:Q1',
    dueDescription: '31st July for Q1 (April–June)',
    penalty: '₹200/day late fee u/s 427 (formerly 234E; max = TDS amount). Penalty u/s 448 (formerly 271H): ₹10,000–₹1,00,000.',
    isCritical: true,
    documentsRequired: ['Form 24Q (salary TDS)', 'Form 26Q (non-salary TDS)', 'Challan details'],
    sourceUrl: 'https://www.tdscpc.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'Every entity making payments subject to TDS must deduct and file returns. Practically all companies. IT Act 2025 (effective 1 April 2026) consolidates TDS into Sec 393; forms renumbered 24Q/26Q → 140, 27Q → 144. Rates, thresholds, and due dates unchanged.',
    applicabilityReason: 'Any entity deducting TDS must file quarterly TDS returns',
  },

  {
    id: 'tds-return-q2',
    name: 'TDS Return (Form 24Q/26Q) — Q2',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 200(3)',
    authority: 'Income Tax Department (TRACES)',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:oct31,covers:Q2',
    dueDescription: '31st October for Q2 (July–September)',
    penalty: '₹200/day late fee u/s 427 (formerly 234E). Penalty u/s 448 (formerly 271H): ₹10,000–₹1,00,000.',
    isCritical: true,
    documentsRequired: ['Form 140 (salary + non-salary TDS; formerly 24Q/26Q)', 'Form 144 (non-resident TDS; formerly 27Q)', 'Challan details'],
    sourceUrl: 'https://www.tdscpc.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'IT Act 2025 (effective 1 April 2026) consolidates TDS into Sec 393; forms renumbered 24Q/26Q → 140, 27Q → 144. Rates, thresholds, and due dates unchanged.',
    applicabilityReason: 'Any entity deducting TDS must file quarterly TDS returns',
  },

  {
    id: 'tds-return-q3',
    name: 'TDS Return (Form 24Q/26Q) — Q3',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 200(3)',
    authority: 'Income Tax Department (TRACES)',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:jan31,covers:Q3',
    dueDescription: '31st January for Q3 (October–December)',
    penalty: '₹200/day late fee u/s 427 (formerly 234E). Penalty u/s 448 (formerly 271H): ₹10,000–₹1,00,000.',
    isCritical: true,
    documentsRequired: ['Form 140 (salary + non-salary TDS; formerly 24Q/26Q)', 'Form 144 (non-resident TDS; formerly 27Q)', 'Challan details'],
    sourceUrl: 'https://www.tdscpc.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'IT Act 2025 (effective 1 April 2026) consolidates TDS into Sec 393; forms renumbered 24Q/26Q → 140, 27Q → 144. Rates, thresholds, and due dates unchanged.',
    applicabilityReason: 'Any entity deducting TDS must file quarterly TDS returns',
  },

  {
    id: 'tds-return-q4',
    name: 'TDS Return (Form 24Q/26Q) — Q4',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 200(3)',
    authority: 'Income Tax Department (TRACES)',
    frequency: 'quarterly',
    dueDateFormula: 'fixed:may31,covers:Q4',
    dueDescription: '31st May for Q4 (January–March)',
    penalty: '₹200/day late fee u/s 427 (formerly 234E). Penalty u/s 448 (formerly 271H): ₹10,000–₹1,00,000.',
    isCritical: true,
    documentsRequired: ['Form 140 (salary + non-salary TDS; formerly 24Q/26Q)', 'Form 144 (non-resident TDS; formerly 27Q)', 'Challan details'],
    sourceUrl: 'https://www.tdscpc.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'IT Act 2025 (effective 1 April 2026) consolidates TDS into Sec 393; forms renumbered 24Q/26Q → 140, 27Q → 144. Rates, thresholds, and due dates unchanged.',
    applicabilityReason: 'Any entity deducting TDS must file quarterly TDS returns',
  },

  {
    id: 'tds-payment-monthly',
    name: 'TDS Payment to Government — Monthly',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Rule 30 of Income Tax Rules',
    authority: 'Income Tax Department',
    frequency: 'monthly',
    dueDateFormula: 'day:7,offset:+1month',
    dueDescription: '7th of the following month (March TDS due 30th April)',
    penalty: 'Interest u/s 201(1A) at 1.5% per month from date of deduction to date of payment',
    isCritical: true,
    documentsRequired: ['Challan 281'],
    sourceUrl: 'https://incometaxindia.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'Every entity deducting TDS must deposit it with the government by the 7th of the following month',
  },

  // ── DIN KYC ─────────────────────────────────────────────────────────────

  {
    id: 'din-kyc-annual',
    name: 'DIR-3 KYC — Annual Director KYC',
    category: 'RoC',
    act: 'Companies Act, 2013',
    section: 'Rule 12A of Companies (Appointment and Qualification of Directors) Rules, 2014',
    authority: 'Ministry of Corporate Affairs (MCA)',
    frequency: 'annual',
    dueDateFormula: 'fixed:sep30',
    dueDescription: '30th September every year',
    penalty: '₹5,000 for late filing. DIN marked as "Deactivated" if not filed.',
    isCritical: true,
    documentsRequired: ['Aadhaar', 'PAN of Director', 'Mobile OTP', 'Email OTP'],
    sourceUrl: 'https://www.mca.gov.in/MinistryV2/dirkyc.html',
    conditions: {},
    effectiveFrom: '2018-07-10',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    notes: 'Every person holding a DIN must file. First-time filers use DIR-3 KYC (form), subsequent use DIR-3 KYC-WEB.',
    applicabilityReason: 'Every director (DIN holder) must complete annual KYC — applies to all companies with directors',
  },

  // ── PAN/TAN ─────────────────────────────────────────────────────────────

  {
    id: 'pan-mandatory',
    name: 'PAN Registration',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 139A',
    authority: 'Income Tax Department',
    frequency: 'one-time',
    dueDateFormula: 'event-based:on_incorporation',
    dueDescription: 'Within 30 days of incorporation / commencement of business',
    penalty: '₹10,000 penalty u/s 272B',
    isCritical: true,
    documentsRequired: ['Certificate of Incorporation', 'Form 49A'],
    sourceUrl: 'https://incometaxindia.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'Every company/entity must obtain PAN',
  },

  {
    id: 'tan-mandatory',
    name: 'TAN Registration',
    category: 'Income Tax',
    act: 'Income Tax Act, 1961',
    section: 'Section 203A',
    authority: 'Income Tax Department',
    frequency: 'one-time',
    dueDateFormula: 'event-based:on_incorporation',
    dueDescription: 'Before first TDS deduction / within 1 month of incorporation',
    penalty: '₹10,000 penalty u/s 272BB',
    isCritical: true,
    documentsRequired: ['Form 49B', 'PAN of Company'],
    sourceUrl: 'https://incometaxindia.gov.in/',
    conditions: {},
    effectiveFrom: '1961-04-01',
    lastVerified: '2026-03-15',
    verifiedBy: 'System',
    applicabilityReason: 'Every entity liable to deduct TDS must obtain TAN',
  },
]
