'use client'

import { useState, useCallback, useEffect, useRef } from 'react'
import {
  loadCIAHistory,
  createCIAConversation,
  addCIAMessage,
  updateCIAMessage,
  renameCIAConversation,
  deleteCIAConversation,
  type DBConversation,
  type DBMessage,
} from '@/app/data-room/actions-cia'

export interface CIAMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  sources?: { name: string; similarity: number }[]
  timestamp: number
}

export interface CIAConversation {
  id: string
  name: string
  messages: CIAMessage[]
  createdAt: number
  updatedAt: number
}

export function useCIAHistory(companyId: string, userId?: string) {
  const [conversations, setConversations] = useState<CIAConversation[]>([])
  const [activeConversationId, setActiveConversationId] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  // Load from DB on mount / company change
  useEffect(() => {
    if (!companyId || !userId) return
    let cancelled = false
    setIsLoading(true)
    loadCIAHistory(companyId, userId).then((loaded) => {
      if (cancelled) return
      setConversations(loaded)
      setActiveConversationId(null)
      setIsLoading(false)
    }).catch(() => {
      if (!cancelled) setIsLoading(false)
    })
    return () => { cancelled = true }
  }, [companyId, userId])

  const activeConversation = conversations.find(c => c.id === activeConversationId) || null

  const createConversation = useCallback(async (): Promise<string> => {
    if (!userId) return ''
    const id = await createCIAConversation(companyId, userId)
    const conv: CIAConversation = {
      id,
      name: 'New Chat',
      messages: [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }
    setConversations(prev => [conv, ...prev])
    setActiveConversationId(id)
    return id
  }, [companyId, userId])

  const addMessage = useCallback(async (
    conversationId: string,
    message: Omit<CIAMessage, 'id' | 'timestamp'>
  ): Promise<string> => {
    // Optimistic local update with temp ID
    const tempId = `temp-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
    const newMsg: CIAMessage = { ...message, id: tempId, timestamp: Date.now() }
    setConversations(prev =>
      prev.map(c =>
        c.id === conversationId
          ? { ...c, messages: [...c.messages, newMsg], updatedAt: Date.now() }
          : c
      )
    )
    // Persist to DB
    const dbId = await addCIAMessage(conversationId, message.role, message.content, message.sources)
    // Replace temp ID with real DB ID
    setConversations(prev =>
      prev.map(c =>
        c.id === conversationId
          ? { ...c, messages: c.messages.map(m => m.id === tempId ? { ...m, id: dbId } : m) }
          : c
      )
    )
    return dbId
  }, [])

  const updateLastAssistantMessage = useCallback(async (
    conversationId: string,
    content: string,
    sources?: { name: string; similarity: number }[],
    knownDbId?: string | null,
  ) => {
    let resolvedDbId: string | null = null
    setConversations(prev =>
      prev.map(c => {
        if (c.id !== conversationId) return c
        const msgs = [...c.messages]
        for (let i = msgs.length - 1; i >= 0; i--) {
          if (msgs[i].role === 'assistant') {
            // If caller passed a DB id, prefer it — it was generated by the
            // add-assistant call and is more trustworthy than whatever tempId
            // is currently on the optimistic message.
            const existingId = msgs[i].id
            const id = knownDbId || (existingId && !existingId.startsWith('temp-') ? existingId : existingId)
            msgs[i] = { ...msgs[i], id, content, ...(sources ? { sources } : {}) }
            if (id && !id.startsWith('temp-')) resolvedDbId = id
            break
          }
        }
        return { ...c, messages: msgs, updatedAt: Date.now() }
      })
    )
    const dbId = knownDbId && !knownDbId.startsWith('temp-') ? knownDbId : resolvedDbId
    if (dbId) {
      await updateCIAMessage(dbId, content, sources).catch(err => {
        console.error('[CIA] updateLastAssistantMessage db write failed', err)
      })
    } else {
      console.warn('[CIA] updateLastAssistantMessage: no DB id available, skipped persist')
    }
  }, [])

  const renameConversation = useCallback(async (conversationId: string, name: string) => {
    setConversations(prev =>
      prev.map(c => (c.id === conversationId ? { ...c, name } : c))
    )
    await renameCIAConversation(conversationId, name).catch(() => {})
  }, [])

  const deleteConversation = useCallback(async (conversationId: string) => {
    setConversations(prev => prev.filter(c => c.id !== conversationId))
    if (activeConversationId === conversationId) {
      setActiveConversationId(null)
    }
    await deleteCIAConversation(conversationId).catch(() => {})
  }, [activeConversationId])

  return {
    conversations: conversations.sort((a, b) => b.updatedAt - a.updatedAt),
    activeConversation,
    activeConversationId,
    setActiveConversationId,
    createConversation,
    addMessage,
    updateLastAssistantMessage,
    renameConversation,
    deleteConversation,
    isLoading,
  }
}
